# Generated by Django 2.2 on 2020-10-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuType', models.CharField(max_length=10, verbose_name='分类')),
                ('CreateType', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='MenuModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=30, verbose_name='菜名')),
                ('MenuImg', models.ImageField(blank=True, default='static/img/plants/default.png', max_length=200, null=True, upload_to='static/img/plants/', verbose_name='图片')),
                ('MenuCore', models.CharField(blank=True, default='3.9', max_length=20, null=True, verbose_name='评分')),
                ('MenuShell', models.CharField(blank=True, default='460', max_length=20, null=True, verbose_name='月销售量')),
                ('MenuFree', models.CharField(blank=True, default='13.1', max_length=20, null=True, verbose_name='价格')),
                ('CreateMenu', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('MenuType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menutype', to='Myrestaurant.MenuType', verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='LovableModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateMenu', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('LoveMune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loveMune', to='Myrestaurant.MenuModels', verbose_name='所喜欢类型')),
                ('LoveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lovableuser', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
