# Generated by Django 2.2 on 2020-10-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lovablemodels',
            options={'ordering': ['CreateMenu'], 'verbose_name': '喜好', 'verbose_name_plural': '喜好'},
        ),
        migrations.AlterModelOptions(
            name='menumodels',
            options={'ordering': ['CreateMenu'], 'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelOptions(
            name='menutype',
            options={'ordering': ['CreateType'], 'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuCore',
            field=models.CharField(blank=True, default='3.1', max_length=20, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuFree',
            field=models.CharField(blank=True, default='14.2', max_length=20, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuShell',
            field=models.CharField(blank=True, default='320', max_length=20, null=True, verbose_name='月销售量'),
        ),
    ]
