# Generated by Django 2.2 on 2020-10-14 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Myrestaurant', '0002_auto_20201013_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodels',
            name='MenuCore',
            field=models.CharField(blank=True, default='1.3', max_length=20, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuFree',
            field=models.CharField(blank=True, default='6.0', max_length=20, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuShell',
            field=models.CharField(blank=True, default='490', max_length=20, null=True, verbose_name='月销售量'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateMenu', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('History_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histor_name', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('OrderMune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Myrestaurant.MenuModels', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['CreateMenu'],
            },
        ),
    ]
