# Generated by Django 2.2 on 2020-10-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0004_auto_20201015_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodels',
            name='MenuCore',
            field=models.CharField(blank=True, default='2.4', max_length=20, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuFree',
            field=models.CharField(blank=True, default='13.9', max_length=20, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuShell',
            field=models.CharField(blank=True, default='602', max_length=20, null=True, verbose_name='月销售量'),
        ),
    ]
