# Generated by Django 2.2 on 2021-01-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0005_auto_20201017_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodels',
            name='MenuCore',
            field=models.CharField(blank=True, default='2.2', max_length=20, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuFree',
            field=models.CharField(blank=True, default='14.3', max_length=20, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='menumodels',
            name='MenuShell',
            field=models.CharField(blank=True, default='405', max_length=20, null=True, verbose_name='月销售量'),
        ),
    ]
